### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ghost** [a4k-openproject/plugin.program.openwizard#133]
**Describe the bug**
I cant update my wizard, i have uploaded a new wizard version, made sure to update version number in addon.xml aswell.
I have uploaded my newset wizard to dropbox and changed the version number on there aswell but when im trying to install new wizard as a test run im getting errors:

EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument for function given by name ('nolabel') and position (3)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.spinstaller/startup.py", line 381, in <module>
                                                       update.wizard_update()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.spinstaller/resources/libs/update.py", line 46, in wizard_update
                                                       yes = dialog.yesno(CONFIG.ADDONTITLE,
                                                   TypeError: argument for function given by name ('nolabel') and position (3)
                                                   -->End of Python script error report<--

This is happening on kodi 19.1(NVIDIA SHIELD ANDROID TV)

Apologies in advance if i caused this error but ive double checked everything i could and cant find the source of error.

**Comment by drinfernoo** [comment]
Have you edited that code? The stock wizard should not have an error in that spot.

**Comment by ghost** [comment]
Not that im aware of, i couldnt understand the error to be honest, i
compared my default.py to the stock one and it doesnt look any different,
im using a builds file which is in standard .txt format on dropbox, should
it be in a different format and does it have to be strictly named
"builds.txt" because mine is named autobuilds.txt

**Comment by ghost** [comment]
Ill try replacing and re-editing the necessary files with ones from the stock wizard

**Comment by drinfernoo** [comment]
This error is in `update.py`, so if you haven't edited that, then something else is going on.

The error doesn't appear (at first glance) to have anything to do with your text files, but if you're able to link them here, that may help me replicate it.

**Comment by ghost** [comment]
I just started on a new one to eliminate all of my errors, i had this wizard going since march and its my first matrix one so i definately messed up somewhere, i appreciate your quick replies and efforts in making the addon to begin with, many thanks

**Comment by pauly001** [comment]
I have the exact same issue with mine as well. Same error in resources/libs/update.py on line 46. My Kodi 18 version works perfectly fine when using my builds.txt file to auto-update. I do not have a repository so I rely on the built-in updater. My wizard is at http://crabbytech.com/test/plugin.program.kodikreationswizard.zip. The builds.txt file is in the same directory. Any help will be much appreciated. Aside from the update giving an error,everything else in the wizard works great.

2021-06-10 16:33:00.517 T:1868     INFO <general>: [COLOR limegreen][B]Kodi Kreations[/B][/COLOR]Wizard: [First Run] Skipping Save Data Settings
2021-06-10 16:33:00.723 T:1868     INFO <general>: [COLOR limegreen][B]Kodi Kreations[/B][/COLOR]Wizard: [Current Build Check] Build Installed: 
2021-06-10 16:33:00.733 T:1868     INFO <general>: [COLOR limegreen][B]Kodi Kreations[/B][/COLOR]Wizard: [Build Update Check] Next Check: 2021-06-10 15:32:49
2021-06-10 16:33:00.733 T:1868     INFO <general>: [COLOR limegreen][B]Kodi Kreations[/B][/COLOR]Wizard: [Auto Install Repo] Not Enabled
2021-06-10 16:33:00.734 T:1868     INFO <general>: [COLOR limegreen][B]Kodi Kreations[/B][/COLOR]Wizard: [Binary Detection] Eligible Binary Addons to Reinstall
2021-06-10 16:33:00.734 T:1868     INFO <general>: [COLOR limegreen][B]Kodi Kreations[/B][/COLOR]Wizard: [Auto Update Wizard] Started
2021-06-10 16:33:00.990 T:1868    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument for function given by name ('nolabel') and position (3)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\pauly\Desktop\Kodi 19 Matrix\Kodi\portable_data\addons\plugin.program.kodikreationswizard\startup.py", line 381, in <module>
                                                       update.wizard_update()
                                                     File "C:\Users\pauly\Desktop\Kodi 19 Matrix\Kodi\portable_data\addons\plugin.program.kodikreationswizard\resources\libs\update.py", line 46, in wizard_update
                                                       yes = dialog.yesno(CONFIG.ADDONTITLE,
                                                   TypeError: argument for function given by name ('nolabel') and position (3)
                                                   -->End of Python script error report<--
                                                   
2021-06-10 16:33:01.010 T:1868     INFO <general>: Python interpreter stopped
2021-06-10 16:33:03.417 T:7644     INFO <general>: CIRServerSuite::Process: failed to connect to irss, will keep retrying every 5 seconds
2021-06-10 16:33:05.375 T:2264     INFO <general>: CPythonInvoker(2, C:\Users\pauly\Desktop\Kodi 19 Matrix\Kodi\portable_data\addons\service.xbmc.versioncheck\resources\lib\runner.py): script successfully run
2021-06-10 16:33:05.381 T:2264     INFO <general>: Python interpreter stopped

**Comment by drinfernoo** [comment]
You both need to update your code to whatever is on the latest `matrix` branch. This issue was fixed back in March.
