### ISSUE TITLE
"Auto Install Repo If Not Installed" does not work

### ISSUE THREAD

**Issue by The-Red-Wizard** [a4k-openproject/plugin.program.openwizard#79]
**Describe the bug**

"Auto Install Repo If Not Installed" does not work and causes Wizard to error when AUTOINSTALL = 'Yes'.

Probably something I am doing wrong, but last worked for me in Aftermath v0.5.0.  I have tried everything I can think of to fix it myself and across several versions of OpenWizard.

**To Reproduce**

Setup "Auto Install Repo If Not Installed" as per instructions.

**Expected behavior**

Specified repo to download and install.

**Platform**

Windows 10 and Kodi 18.5 64-bit

**Additional context**

Kodi log:

2020-03-07 18:17:20.703 T:956  NOTICE: OneAlliance Reborn Wizard: [Path Check] Started
2020-03-07 18:17:20.753 T:956  NOTICE: OneAlliance Reborn Wizard: [Path Check] Good!
2020-03-07 18:17:20.801 T:956  NOTICE: OneAlliance Reborn Wizard: [First Run] Showing Save Data Settings
2020-03-07 18:17:35.424 T:956  NOTICE: OneAlliance Reborn Wizard: URL check passed for http://repo.1ar.cc/wizard/autobuilds.txt: Status code [200]
2020-03-07 18:17:35.486 T:956  NOTICE: OneAlliance Reborn Wizard: [Current Build Check] Build Not Installed
2020-03-07 18:17:37.294 T:956  NOTICE: OneAlliance Reborn Wizard: [Current Build Check] [User Selected: Ignore Build Menu] [Next Check: 2019-01-01 00:00:00]
2020-03-07 18:17:37.438 T:956  NOTICE: OneAlliance Reborn Wizard: [Build Update Check] Next Check: 2020-03-07 18:17:37
2020-03-07 18:17:37.479 T:956  NOTICE: OneAlliance Reborn Wizard: [Auto Install Repo] Started
2020-03-07 18:17:37.612 T:956  NOTICE: OneAlliance Reborn Wizard: URL check passed for http://repo.1ar.cc/1ARebornRepo/addons.xml: Status code [200]
2020-03-07 18:17:37.968 T:956   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xed' in position 5026: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\alunh\Builds\Windows\1A Test_18.5\Kodi\portable_data\addons\plugin.program.onealliancerebornwizard\startup.py", line 373, in <module>
                                                auto_install_repo()
                                              File "C:\Users\alunh\Builds\Windows\1A Test_18.5\Kodi\portable_data\addons\plugin.program.onealliancerebornwizard\startup.py", line 53, in auto_install_repo
                                                root = ElementTree.fromstring(response.text)
                                              File "C:\Users\alunh\Builds\Windows\1A Test_18.5\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1311, in XML
                                                parser.feed(text)
                                              File "C:\Users\alunh\Builds\Windows\1A Test_18.5\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1651, in feed
                                                self._parser.Parse(data, 0)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 5026: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by drinfernoo** [comment]
Take it up with One Alliance. That's a different wizard.

**Comment by The-Red-Wizard** [comment]
Hello,

It is not a different Wizard.  The most recent version where we tried to get this to work was OpenWizard v1.3.2, with OneAlliance name, urls and icon, etc.  However, we have tried other versions of OpenWizard too.  As I wrote above, the last version where we could get this feature to work was Aftermath v0.5.0.
