### ISSUE TITLE
"Auto Install Repo If Not Installed" does not work [Bug]

### ISSUE THREAD

**Issue by The-Red-Wizard** [a4k-openproject/plugin.program.openwizard#80]
**Describe the bug**
"Auto Install Repo If Not Installed" does not work and causes Wizard to error when AUTOINSTALL = 'Yes'.  Previously Issue #79 (closed).  Last worked for me in Aftermath v0.5.0.

This time I used OpenWizard v1.3.4 with only OneAlliance repo url changes (everything else is OpenWizard).  Then did the same again with OpenWizard repo urls.

**To Reproduce**

Setup "Auto Install Repo If Not Installed" as per instructions.

**Expected behavior**

Specified repo to download and install.

**Screenshots**

**Platform**
Windows 10 and Kodi 18.6 64-bit.  Also tried Android Kodi 18.6 64-bit.

**Additional context**
Kodi log:

2020-04-01 08:04:09.907 T:1572  NOTICE: [COLOR limegreen][B]Open[/B][/COLOR]Wizard: [Path Check] Started
2020-04-01 08:04:10.117 T:1572  NOTICE: [COLOR limegreen][B]Open[/B][/COLOR]Wizard: [Path Check] Good!
2020-04-01 08:04:10.165 T:1572  NOTICE: [COLOR limegreen][B]Open[/B][/COLOR]Wizard: [First Run] Showing Save Data Settings
2020-04-01 08:04:17.995 T:1572  NOTICE: [COLOR limegreen][B]Open[/B][/COLOR]Wizard: URL is not of a valid schema: http://
2020-04-01 08:04:18.029 T:1572  NOTICE: [COLOR limegreen][B]Open[/B][/COLOR]Wizard: [Current Build Check] Build Installed:
2020-04-01 08:04:18.078 T:1572  NOTICE: [COLOR limegreen][B]Open[/B][/COLOR]Wizard: [Build Update Check] Next Check: 2019-01-01 00:00:00
2020-04-01 08:04:18.112 T:1572  NOTICE: [COLOR limegreen][B]Open[/B][/COLOR]Wizard: [Auto Install Repo] Started
2020-04-01 08:04:18.404 T:1572  NOTICE: [COLOR limegreen][B]Open[/B][/COLOR]Wizard: URL check passed for http://repo.1ar.cc/1ARebornRepo/addons.xml: Status code [200]
2020-04-01 08:04:18.953 T:1572   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xed' in position 5026: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\alunh\Builds\Windows\Test_18.6_x64\Kodi\portable_data\addons\plugin.program.openwizard\startup.py", line 373, in <module>
                                                auto_install_repo()
                                              File "C:\Users\alunh\Builds\Windows\Test_18.6_x64\Kodi\portable_data\addons\plugin.program.openwizard\startup.py", line 53, in auto_install_repo
                                                root = ElementTree.fromstring(response.text)
                                              File "C:\Users\alunh\Builds\Windows\Test_18.6_x64\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1311, in XML
                                                parser.feed(text)
                                              File "C:\Users\alunh\Builds\Windows\Test_18.6_x64\Kodi\system\python\Lib\xml\etree\ElementTree.py", line 1651, in feed
                                                self._parser.Parse(data, 0)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 5026: ordinal not in range(128)
                                            -->End of Python script error report<--
2020-04-01 08:05:03.146 T:8608  NOTICE: Stopping player
2020-04-01 08:05:03.146 T:8608  NOTICE: Storing total System Uptime
2020-04-01 08:05:03.146 T:8608  NOTICE: Saving settings
2020-04-01 08:05:03.170 T:8608  NOTICE: Saving skin settings
2020-04-01 08:05:03.175 T:8608  NOTICE: Stopping all
2020-04-01 08:05:03.175 T:8608  NOTICE: ES: Stopping event server
2020-04-01 08:05:04.047 T:18300  NOTICE: ES: UDP Event server stopped
2020-04-01 08:05:04.112 T:8608  NOTICE: Application stopped
2020-04-01 08:05:04.312 T:8608  NOTICE: XBApplicationEx: destroying...
2020-04-01 08:05:04.417 T:8608  NOTICE: unload skin
2020-04-01 08:05:04.636 T:8608  NOTICE: unload sections
2020-04-01 08:05:04.656 T:8608  NOTICE: XBApplicationEx: application stopped!

**Comment by The-Red-Wizard** [comment]
I have just tried the OpenWizard repo urls with the intention of uploading the log, but it works.  Apologies for wasting your time.  I am at a loss as to why the OneAlliance urls do not work.  I have tried with countless different permissions in the cloud including no restrictions at all.
