### ISSUE TITLE
[Kodi19] Stock  - Install bug report 

### ISSUE THREAD

**Issue by SerpentDrago** [a4k-openproject/plugin.program.openwizard#93]
All tests done on windows 10 PC , with kodi 19 latest dev x64

**Install issues** 
1. 
`2020-04-22 09:48:01.636 T:22828   ERROR <general>: CAddonInstallJob[plugin.program.openwizard]: The dependency on xbmc.python version 2.1.0 could not be satisfied.`

Fixed by removing 
`<import addon="xbmc.python" version="2.1.0" />`
From addon.xml

2. IT now installed , only with a single openwizard error at the very end of install 

```
2020-04-22 09:53:14.708 T:22732   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: function takes at most 2 arguments (4 given)
                                                   Traceback (most recent call last):
                                                     File "X:\Kodi\Kodi 19\portable_data\addons\plugin.program.openwizard\startup.py", line 339, in <module>
                                                       check.check_paths()
                                                     File "X:\Kodi\Kodi 19\portable_data\addons\plugin.program.openwizard\resources\libs\check.py", line 53, in check_paths
                                                       path))
                                                   TypeError: function takes at most 2 arguments (4 given)
                                                   -->End of Python script error report<--
```

3. now with it installed , tried to run it (it showed as installed even after that first error) . It then had error and failed to open 

```
2020-04-22 09:55:36.610 T:20224   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'iconImage' is an invalid keyword argument for this function
                                                   Traceback (most recent call last):
                                                     File "X:\Kodi\Kodi 19\portable_data\addons\plugin.program.openwizard\default.py", line 29, in <module>
                                                       dispatcher.dispatch(_handle, _params)
                                                     File "X:\Kodi\Kodi 19\portable_data\addons\plugin.program.openwizard\resources\libs\common\router.py", line 48, in dispatch
                                                       MainMenu().get_listing()
                                                     File "X:\Kodi\Kodi 19\portable_data\addons\plugin.program.openwizard\resources\libs\gui\main_menu.py", line 52, in get_listing
                                                       themeit=CONFIG.THEME2)
                                                     File "X:\Kodi\Kodi 19\portable_data\addons\plugin.program.openwizard\resources\libs\common\directory.py", line 61, in add_file
                                                       _add_menu_item(display, params, menu, description, overwrite, fanart, icon, themeit, isFolder)
                                                     File "X:\Kodi\Kodi 19\portable_data\addons\plugin.program.openwizard\resources\libs\common\directory.py", line 90, in _add_menu_item
                                                       liz = xbmcgui.ListItem(display, iconImage="DefaultFolder.png", thumbnailImage=icon)
                                                   TypeError: 'iconImage' is an invalid keyword argument for this function
                                                   -->End of Python script error report<--
```

[kodi.log](https://github.com/drinfernoo/plugin.program.openwizard/files/4516519/kodi.log)

Log attached .  

I'll leave you with those issues first , and once all fixed move on to more kodi 19 testing

**Comment by drinfernoo** [comment]
Kodi 19 support has been added as of 2.0.0.
